// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CombinedSportsColumns holds the columns for the "combined_sports" table.
	CombinedSportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "country", Type: field.TypeString},
		{Name: "sport", Type: field.TypeString},
		{Name: "gold", Type: field.TypeInt},
		{Name: "silver", Type: field.TypeInt},
		{Name: "bronze", Type: field.TypeInt},
		{Name: "points", Type: field.TypeInt},
		{Name: "total_score", Type: field.TypeInt},
		{Name: "population", Type: field.TypeInt},
		{Name: "per_capita", Type: field.TypeFloat64},
	}
	// CombinedSportsTable holds the schema information for the "combined_sports" table.
	CombinedSportsTable = &schema.Table{
		Name:       "combined_sports",
		Columns:    CombinedSportsColumns,
		PrimaryKey: []*schema.Column{CombinedSportsColumns[0]},
	}
	// IndividualSportsColumns holds the columns for the "individual_sports" table.
	IndividualSportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "country", Type: field.TypeString},
		{Name: "sport", Type: field.TypeString},
		{Name: "gold", Type: field.TypeInt},
		{Name: "silver", Type: field.TypeInt},
		{Name: "bronze", Type: field.TypeInt},
		{Name: "points", Type: field.TypeInt},
		{Name: "total_score", Type: field.TypeInt},
		{Name: "population", Type: field.TypeInt},
		{Name: "per_capita", Type: field.TypeFloat64},
	}
	// IndividualSportsTable holds the schema information for the "individual_sports" table.
	IndividualSportsTable = &schema.Table{
		Name:       "individual_sports",
		Columns:    IndividualSportsColumns,
		PrimaryKey: []*schema.Column{IndividualSportsColumns[0]},
	}
	// TeamSportsColumns holds the columns for the "team_sports" table.
	TeamSportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "country", Type: field.TypeString},
		{Name: "sport", Type: field.TypeString},
		{Name: "gold", Type: field.TypeInt},
		{Name: "silver", Type: field.TypeInt},
		{Name: "bronze", Type: field.TypeInt},
		{Name: "points", Type: field.TypeInt},
		{Name: "total_score", Type: field.TypeInt},
		{Name: "population", Type: field.TypeInt},
		{Name: "per_capita", Type: field.TypeFloat64},
	}
	// TeamSportsTable holds the schema information for the "team_sports" table.
	TeamSportsTable = &schema.Table{
		Name:       "team_sports",
		Columns:    TeamSportsColumns,
		PrimaryKey: []*schema.Column{TeamSportsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CombinedSportsTable,
		IndividualSportsTable,
		TeamSportsTable,
	}
)

func init() {
}
