// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/marko-durasic/olympics/ent/combinedsport"
)

// CombinedSport is the model entity for the CombinedSport schema.
type CombinedSport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Sport holds the value of the "sport" field.
	Sport string `json:"sport,omitempty"`
	// Gold holds the value of the "gold" field.
	Gold int `json:"gold,omitempty"`
	// Silver holds the value of the "silver" field.
	Silver int `json:"silver,omitempty"`
	// Bronze holds the value of the "bronze" field.
	Bronze int `json:"bronze,omitempty"`
	// Points holds the value of the "points" field.
	Points int `json:"points,omitempty"`
	// TotalScore holds the value of the "total_score" field.
	TotalScore int `json:"total_score,omitempty"`
	// Population holds the value of the "population" field.
	Population int `json:"population,omitempty"`
	// PerCapita holds the value of the "per_capita" field.
	PerCapita    float64 `json:"per_capita,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CombinedSport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case combinedsport.FieldPerCapita:
			values[i] = new(sql.NullFloat64)
		case combinedsport.FieldID, combinedsport.FieldGold, combinedsport.FieldSilver, combinedsport.FieldBronze, combinedsport.FieldPoints, combinedsport.FieldTotalScore, combinedsport.FieldPopulation:
			values[i] = new(sql.NullInt64)
		case combinedsport.FieldCountry, combinedsport.FieldSport:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CombinedSport fields.
func (cs *CombinedSport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case combinedsport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cs.ID = int(value.Int64)
		case combinedsport.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				cs.Country = value.String
			}
		case combinedsport.FieldSport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sport", values[i])
			} else if value.Valid {
				cs.Sport = value.String
			}
		case combinedsport.FieldGold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold", values[i])
			} else if value.Valid {
				cs.Gold = int(value.Int64)
			}
		case combinedsport.FieldSilver:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field silver", values[i])
			} else if value.Valid {
				cs.Silver = int(value.Int64)
			}
		case combinedsport.FieldBronze:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bronze", values[i])
			} else if value.Valid {
				cs.Bronze = int(value.Int64)
			}
		case combinedsport.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				cs.Points = int(value.Int64)
			}
		case combinedsport.FieldTotalScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_score", values[i])
			} else if value.Valid {
				cs.TotalScore = int(value.Int64)
			}
		case combinedsport.FieldPopulation:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field population", values[i])
			} else if value.Valid {
				cs.Population = int(value.Int64)
			}
		case combinedsport.FieldPerCapita:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field per_capita", values[i])
			} else if value.Valid {
				cs.PerCapita = value.Float64
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CombinedSport.
// This includes values selected through modifiers, order, etc.
func (cs *CombinedSport) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// Update returns a builder for updating this CombinedSport.
// Note that you need to call CombinedSport.Unwrap() before calling this method if this CombinedSport
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CombinedSport) Update() *CombinedSportUpdateOne {
	return NewCombinedSportClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the CombinedSport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CombinedSport) Unwrap() *CombinedSport {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CombinedSport is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CombinedSport) String() string {
	var builder strings.Builder
	builder.WriteString("CombinedSport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("country=")
	builder.WriteString(cs.Country)
	builder.WriteString(", ")
	builder.WriteString("sport=")
	builder.WriteString(cs.Sport)
	builder.WriteString(", ")
	builder.WriteString("gold=")
	builder.WriteString(fmt.Sprintf("%v", cs.Gold))
	builder.WriteString(", ")
	builder.WriteString("silver=")
	builder.WriteString(fmt.Sprintf("%v", cs.Silver))
	builder.WriteString(", ")
	builder.WriteString("bronze=")
	builder.WriteString(fmt.Sprintf("%v", cs.Bronze))
	builder.WriteString(", ")
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", cs.Points))
	builder.WriteString(", ")
	builder.WriteString("total_score=")
	builder.WriteString(fmt.Sprintf("%v", cs.TotalScore))
	builder.WriteString(", ")
	builder.WriteString("population=")
	builder.WriteString(fmt.Sprintf("%v", cs.Population))
	builder.WriteString(", ")
	builder.WriteString("per_capita=")
	builder.WriteString(fmt.Sprintf("%v", cs.PerCapita))
	builder.WriteByte(')')
	return builder.String()
}

// CombinedSports is a parsable slice of CombinedSport.
type CombinedSports []*CombinedSport
