// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marko-durasic/olympics/ent/combinedsport"
	"github.com/marko-durasic/olympics/ent/predicate"
)

// CombinedSportQuery is the builder for querying CombinedSport entities.
type CombinedSportQuery struct {
	config
	ctx        *QueryContext
	order      []combinedsport.OrderOption
	inters     []Interceptor
	predicates []predicate.CombinedSport
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CombinedSportQuery builder.
func (csq *CombinedSportQuery) Where(ps ...predicate.CombinedSport) *CombinedSportQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *CombinedSportQuery) Limit(limit int) *CombinedSportQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *CombinedSportQuery) Offset(offset int) *CombinedSportQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *CombinedSportQuery) Unique(unique bool) *CombinedSportQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *CombinedSportQuery) Order(o ...combinedsport.OrderOption) *CombinedSportQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// First returns the first CombinedSport entity from the query.
// Returns a *NotFoundError when no CombinedSport was found.
func (csq *CombinedSportQuery) First(ctx context.Context) (*CombinedSport, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{combinedsport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *CombinedSportQuery) FirstX(ctx context.Context) *CombinedSport {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CombinedSport ID from the query.
// Returns a *NotFoundError when no CombinedSport ID was found.
func (csq *CombinedSportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{combinedsport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *CombinedSportQuery) FirstIDX(ctx context.Context) int {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CombinedSport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CombinedSport entity is found.
// Returns a *NotFoundError when no CombinedSport entities are found.
func (csq *CombinedSportQuery) Only(ctx context.Context) (*CombinedSport, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{combinedsport.Label}
	default:
		return nil, &NotSingularError{combinedsport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *CombinedSportQuery) OnlyX(ctx context.Context) *CombinedSport {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CombinedSport ID in the query.
// Returns a *NotSingularError when more than one CombinedSport ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *CombinedSportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{combinedsport.Label}
	default:
		err = &NotSingularError{combinedsport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *CombinedSportQuery) OnlyIDX(ctx context.Context) int {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CombinedSports.
func (csq *CombinedSportQuery) All(ctx context.Context) ([]*CombinedSport, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryAll)
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CombinedSport, *CombinedSportQuery]()
	return withInterceptors[[]*CombinedSport](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *CombinedSportQuery) AllX(ctx context.Context) []*CombinedSport {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CombinedSport IDs.
func (csq *CombinedSportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryIDs)
	if err = csq.Select(combinedsport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *CombinedSportQuery) IDsX(ctx context.Context) []int {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *CombinedSportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryCount)
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*CombinedSportQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *CombinedSportQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *CombinedSportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryExist)
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *CombinedSportQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CombinedSportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *CombinedSportQuery) Clone() *CombinedSportQuery {
	if csq == nil {
		return nil
	}
	return &CombinedSportQuery{
		config:     csq.config,
		ctx:        csq.ctx.Clone(),
		order:      append([]combinedsport.OrderOption{}, csq.order...),
		inters:     append([]Interceptor{}, csq.inters...),
		predicates: append([]predicate.CombinedSport{}, csq.predicates...),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CombinedSport.Query().
//		GroupBy(combinedsport.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *CombinedSportQuery) GroupBy(field string, fields ...string) *CombinedSportGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CombinedSportGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = combinedsport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.CombinedSport.Query().
//		Select(combinedsport.FieldCountry).
//		Scan(ctx, &v)
func (csq *CombinedSportQuery) Select(fields ...string) *CombinedSportSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &CombinedSportSelect{CombinedSportQuery: csq}
	sbuild.label = combinedsport.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CombinedSportSelect configured with the given aggregations.
func (csq *CombinedSportQuery) Aggregate(fns ...AggregateFunc) *CombinedSportSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *CombinedSportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !combinedsport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *CombinedSportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CombinedSport, error) {
	var (
		nodes = []*CombinedSport{}
		_spec = csq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CombinedSport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CombinedSport{config: csq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (csq *CombinedSportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *CombinedSportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(combinedsport.Table, combinedsport.Columns, sqlgraph.NewFieldSpec(combinedsport.FieldID, field.TypeInt))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, combinedsport.FieldID)
		for i := range fields {
			if fields[i] != combinedsport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *CombinedSportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(combinedsport.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = combinedsport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CombinedSportGroupBy is the group-by builder for CombinedSport entities.
type CombinedSportGroupBy struct {
	selector
	build *CombinedSportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *CombinedSportGroupBy) Aggregate(fns ...AggregateFunc) *CombinedSportGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *CombinedSportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, ent.OpQueryGroupBy)
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CombinedSportQuery, *CombinedSportGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *CombinedSportGroupBy) sqlScan(ctx context.Context, root *CombinedSportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CombinedSportSelect is the builder for selecting fields of CombinedSport entities.
type CombinedSportSelect struct {
	*CombinedSportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *CombinedSportSelect) Aggregate(fns ...AggregateFunc) *CombinedSportSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *CombinedSportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, ent.OpQuerySelect)
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CombinedSportQuery, *CombinedSportSelect](ctx, css.CombinedSportQuery, css, css.inters, v)
}

func (css *CombinedSportSelect) sqlScan(ctx context.Context, root *CombinedSportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
