// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marko-durasic/olympics/ent/combinedsport"
	"github.com/marko-durasic/olympics/ent/predicate"
)

// CombinedSportDelete is the builder for deleting a CombinedSport entity.
type CombinedSportDelete struct {
	config
	hooks    []Hook
	mutation *CombinedSportMutation
}

// Where appends a list predicates to the CombinedSportDelete builder.
func (csd *CombinedSportDelete) Where(ps ...predicate.CombinedSport) *CombinedSportDelete {
	csd.mutation.Where(ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *CombinedSportDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, csd.sqlExec, csd.mutation, csd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *CombinedSportDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *CombinedSportDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(combinedsport.Table, sqlgraph.NewFieldSpec(combinedsport.FieldID, field.TypeInt))
	if ps := csd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, csd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	csd.mutation.done = true
	return affected, err
}

// CombinedSportDeleteOne is the builder for deleting a single CombinedSport entity.
type CombinedSportDeleteOne struct {
	csd *CombinedSportDelete
}

// Where appends a list predicates to the CombinedSportDelete builder.
func (csdo *CombinedSportDeleteOne) Where(ps ...predicate.CombinedSport) *CombinedSportDeleteOne {
	csdo.csd.mutation.Where(ps...)
	return csdo
}

// Exec executes the deletion query.
func (csdo *CombinedSportDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{combinedsport.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *CombinedSportDeleteOne) ExecX(ctx context.Context) {
	if err := csdo.Exec(ctx); err != nil {
		panic(err)
	}
}
