// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marko-durasic/olympics/ent/individualsport"
	"github.com/marko-durasic/olympics/ent/predicate"
)

// IndividualSportQuery is the builder for querying IndividualSport entities.
type IndividualSportQuery struct {
	config
	ctx        *QueryContext
	order      []individualsport.OrderOption
	inters     []Interceptor
	predicates []predicate.IndividualSport
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IndividualSportQuery builder.
func (isq *IndividualSportQuery) Where(ps ...predicate.IndividualSport) *IndividualSportQuery {
	isq.predicates = append(isq.predicates, ps...)
	return isq
}

// Limit the number of records to be returned by this query.
func (isq *IndividualSportQuery) Limit(limit int) *IndividualSportQuery {
	isq.ctx.Limit = &limit
	return isq
}

// Offset to start from.
func (isq *IndividualSportQuery) Offset(offset int) *IndividualSportQuery {
	isq.ctx.Offset = &offset
	return isq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (isq *IndividualSportQuery) Unique(unique bool) *IndividualSportQuery {
	isq.ctx.Unique = &unique
	return isq
}

// Order specifies how the records should be ordered.
func (isq *IndividualSportQuery) Order(o ...individualsport.OrderOption) *IndividualSportQuery {
	isq.order = append(isq.order, o...)
	return isq
}

// First returns the first IndividualSport entity from the query.
// Returns a *NotFoundError when no IndividualSport was found.
func (isq *IndividualSportQuery) First(ctx context.Context) (*IndividualSport, error) {
	nodes, err := isq.Limit(1).All(setContextOp(ctx, isq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{individualsport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (isq *IndividualSportQuery) FirstX(ctx context.Context) *IndividualSport {
	node, err := isq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IndividualSport ID from the query.
// Returns a *NotFoundError when no IndividualSport ID was found.
func (isq *IndividualSportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = isq.Limit(1).IDs(setContextOp(ctx, isq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{individualsport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (isq *IndividualSportQuery) FirstIDX(ctx context.Context) int {
	id, err := isq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IndividualSport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IndividualSport entity is found.
// Returns a *NotFoundError when no IndividualSport entities are found.
func (isq *IndividualSportQuery) Only(ctx context.Context) (*IndividualSport, error) {
	nodes, err := isq.Limit(2).All(setContextOp(ctx, isq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{individualsport.Label}
	default:
		return nil, &NotSingularError{individualsport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (isq *IndividualSportQuery) OnlyX(ctx context.Context) *IndividualSport {
	node, err := isq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IndividualSport ID in the query.
// Returns a *NotSingularError when more than one IndividualSport ID is found.
// Returns a *NotFoundError when no entities are found.
func (isq *IndividualSportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = isq.Limit(2).IDs(setContextOp(ctx, isq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{individualsport.Label}
	default:
		err = &NotSingularError{individualsport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (isq *IndividualSportQuery) OnlyIDX(ctx context.Context) int {
	id, err := isq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IndividualSports.
func (isq *IndividualSportQuery) All(ctx context.Context) ([]*IndividualSport, error) {
	ctx = setContextOp(ctx, isq.ctx, ent.OpQueryAll)
	if err := isq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IndividualSport, *IndividualSportQuery]()
	return withInterceptors[[]*IndividualSport](ctx, isq, qr, isq.inters)
}

// AllX is like All, but panics if an error occurs.
func (isq *IndividualSportQuery) AllX(ctx context.Context) []*IndividualSport {
	nodes, err := isq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IndividualSport IDs.
func (isq *IndividualSportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if isq.ctx.Unique == nil && isq.path != nil {
		isq.Unique(true)
	}
	ctx = setContextOp(ctx, isq.ctx, ent.OpQueryIDs)
	if err = isq.Select(individualsport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (isq *IndividualSportQuery) IDsX(ctx context.Context) []int {
	ids, err := isq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (isq *IndividualSportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, isq.ctx, ent.OpQueryCount)
	if err := isq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, isq, querierCount[*IndividualSportQuery](), isq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (isq *IndividualSportQuery) CountX(ctx context.Context) int {
	count, err := isq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (isq *IndividualSportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, isq.ctx, ent.OpQueryExist)
	switch _, err := isq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (isq *IndividualSportQuery) ExistX(ctx context.Context) bool {
	exist, err := isq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IndividualSportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (isq *IndividualSportQuery) Clone() *IndividualSportQuery {
	if isq == nil {
		return nil
	}
	return &IndividualSportQuery{
		config:     isq.config,
		ctx:        isq.ctx.Clone(),
		order:      append([]individualsport.OrderOption{}, isq.order...),
		inters:     append([]Interceptor{}, isq.inters...),
		predicates: append([]predicate.IndividualSport{}, isq.predicates...),
		// clone intermediate query.
		sql:  isq.sql.Clone(),
		path: isq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IndividualSport.Query().
//		GroupBy(individualsport.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (isq *IndividualSportQuery) GroupBy(field string, fields ...string) *IndividualSportGroupBy {
	isq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IndividualSportGroupBy{build: isq}
	grbuild.flds = &isq.ctx.Fields
	grbuild.label = individualsport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.IndividualSport.Query().
//		Select(individualsport.FieldCountry).
//		Scan(ctx, &v)
func (isq *IndividualSportQuery) Select(fields ...string) *IndividualSportSelect {
	isq.ctx.Fields = append(isq.ctx.Fields, fields...)
	sbuild := &IndividualSportSelect{IndividualSportQuery: isq}
	sbuild.label = individualsport.Label
	sbuild.flds, sbuild.scan = &isq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IndividualSportSelect configured with the given aggregations.
func (isq *IndividualSportQuery) Aggregate(fns ...AggregateFunc) *IndividualSportSelect {
	return isq.Select().Aggregate(fns...)
}

func (isq *IndividualSportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range isq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, isq); err != nil {
				return err
			}
		}
	}
	for _, f := range isq.ctx.Fields {
		if !individualsport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if isq.path != nil {
		prev, err := isq.path(ctx)
		if err != nil {
			return err
		}
		isq.sql = prev
	}
	return nil
}

func (isq *IndividualSportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IndividualSport, error) {
	var (
		nodes = []*IndividualSport{}
		_spec = isq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IndividualSport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IndividualSport{config: isq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, isq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (isq *IndividualSportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := isq.querySpec()
	_spec.Node.Columns = isq.ctx.Fields
	if len(isq.ctx.Fields) > 0 {
		_spec.Unique = isq.ctx.Unique != nil && *isq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, isq.driver, _spec)
}

func (isq *IndividualSportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(individualsport.Table, individualsport.Columns, sqlgraph.NewFieldSpec(individualsport.FieldID, field.TypeInt))
	_spec.From = isq.sql
	if unique := isq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if isq.path != nil {
		_spec.Unique = true
	}
	if fields := isq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, individualsport.FieldID)
		for i := range fields {
			if fields[i] != individualsport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := isq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := isq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := isq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := isq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (isq *IndividualSportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(isq.driver.Dialect())
	t1 := builder.Table(individualsport.Table)
	columns := isq.ctx.Fields
	if len(columns) == 0 {
		columns = individualsport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if isq.sql != nil {
		selector = isq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if isq.ctx.Unique != nil && *isq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range isq.predicates {
		p(selector)
	}
	for _, p := range isq.order {
		p(selector)
	}
	if offset := isq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := isq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IndividualSportGroupBy is the group-by builder for IndividualSport entities.
type IndividualSportGroupBy struct {
	selector
	build *IndividualSportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (isgb *IndividualSportGroupBy) Aggregate(fns ...AggregateFunc) *IndividualSportGroupBy {
	isgb.fns = append(isgb.fns, fns...)
	return isgb
}

// Scan applies the selector query and scans the result into the given value.
func (isgb *IndividualSportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, isgb.build.ctx, ent.OpQueryGroupBy)
	if err := isgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IndividualSportQuery, *IndividualSportGroupBy](ctx, isgb.build, isgb, isgb.build.inters, v)
}

func (isgb *IndividualSportGroupBy) sqlScan(ctx context.Context, root *IndividualSportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(isgb.fns))
	for _, fn := range isgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*isgb.flds)+len(isgb.fns))
		for _, f := range *isgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*isgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := isgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IndividualSportSelect is the builder for selecting fields of IndividualSport entities.
type IndividualSportSelect struct {
	*IndividualSportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (iss *IndividualSportSelect) Aggregate(fns ...AggregateFunc) *IndividualSportSelect {
	iss.fns = append(iss.fns, fns...)
	return iss
}

// Scan applies the selector query and scans the result into the given value.
func (iss *IndividualSportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iss.ctx, ent.OpQuerySelect)
	if err := iss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IndividualSportQuery, *IndividualSportSelect](ctx, iss.IndividualSportQuery, iss, iss.inters, v)
}

func (iss *IndividualSportSelect) sqlScan(ctx context.Context, root *IndividualSportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(iss.fns))
	for _, fn := range iss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*iss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
