// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marko-durasic/olympics/ent/individualsport"
)

// IndividualSportCreate is the builder for creating a IndividualSport entity.
type IndividualSportCreate struct {
	config
	mutation *IndividualSportMutation
	hooks    []Hook
}

// SetCountry sets the "country" field.
func (isc *IndividualSportCreate) SetCountry(s string) *IndividualSportCreate {
	isc.mutation.SetCountry(s)
	return isc
}

// SetSport sets the "sport" field.
func (isc *IndividualSportCreate) SetSport(s string) *IndividualSportCreate {
	isc.mutation.SetSport(s)
	return isc
}

// SetGold sets the "gold" field.
func (isc *IndividualSportCreate) SetGold(i int) *IndividualSportCreate {
	isc.mutation.SetGold(i)
	return isc
}

// SetSilver sets the "silver" field.
func (isc *IndividualSportCreate) SetSilver(i int) *IndividualSportCreate {
	isc.mutation.SetSilver(i)
	return isc
}

// SetBronze sets the "bronze" field.
func (isc *IndividualSportCreate) SetBronze(i int) *IndividualSportCreate {
	isc.mutation.SetBronze(i)
	return isc
}

// SetPoints sets the "points" field.
func (isc *IndividualSportCreate) SetPoints(i int) *IndividualSportCreate {
	isc.mutation.SetPoints(i)
	return isc
}

// SetTotalScore sets the "total_score" field.
func (isc *IndividualSportCreate) SetTotalScore(i int) *IndividualSportCreate {
	isc.mutation.SetTotalScore(i)
	return isc
}

// SetPopulation sets the "population" field.
func (isc *IndividualSportCreate) SetPopulation(i int) *IndividualSportCreate {
	isc.mutation.SetPopulation(i)
	return isc
}

// SetPerCapita sets the "per_capita" field.
func (isc *IndividualSportCreate) SetPerCapita(f float64) *IndividualSportCreate {
	isc.mutation.SetPerCapita(f)
	return isc
}

// Mutation returns the IndividualSportMutation object of the builder.
func (isc *IndividualSportCreate) Mutation() *IndividualSportMutation {
	return isc.mutation
}

// Save creates the IndividualSport in the database.
func (isc *IndividualSportCreate) Save(ctx context.Context) (*IndividualSport, error) {
	return withHooks(ctx, isc.sqlSave, isc.mutation, isc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (isc *IndividualSportCreate) SaveX(ctx context.Context) *IndividualSport {
	v, err := isc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (isc *IndividualSportCreate) Exec(ctx context.Context) error {
	_, err := isc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (isc *IndividualSportCreate) ExecX(ctx context.Context) {
	if err := isc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (isc *IndividualSportCreate) check() error {
	if _, ok := isc.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "IndividualSport.country"`)}
	}
	if _, ok := isc.mutation.Sport(); !ok {
		return &ValidationError{Name: "sport", err: errors.New(`ent: missing required field "IndividualSport.sport"`)}
	}
	if _, ok := isc.mutation.Gold(); !ok {
		return &ValidationError{Name: "gold", err: errors.New(`ent: missing required field "IndividualSport.gold"`)}
	}
	if _, ok := isc.mutation.Silver(); !ok {
		return &ValidationError{Name: "silver", err: errors.New(`ent: missing required field "IndividualSport.silver"`)}
	}
	if _, ok := isc.mutation.Bronze(); !ok {
		return &ValidationError{Name: "bronze", err: errors.New(`ent: missing required field "IndividualSport.bronze"`)}
	}
	if _, ok := isc.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "IndividualSport.points"`)}
	}
	if _, ok := isc.mutation.TotalScore(); !ok {
		return &ValidationError{Name: "total_score", err: errors.New(`ent: missing required field "IndividualSport.total_score"`)}
	}
	if _, ok := isc.mutation.Population(); !ok {
		return &ValidationError{Name: "population", err: errors.New(`ent: missing required field "IndividualSport.population"`)}
	}
	if _, ok := isc.mutation.PerCapita(); !ok {
		return &ValidationError{Name: "per_capita", err: errors.New(`ent: missing required field "IndividualSport.per_capita"`)}
	}
	return nil
}

func (isc *IndividualSportCreate) sqlSave(ctx context.Context) (*IndividualSport, error) {
	if err := isc.check(); err != nil {
		return nil, err
	}
	_node, _spec := isc.createSpec()
	if err := sqlgraph.CreateNode(ctx, isc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	isc.mutation.id = &_node.ID
	isc.mutation.done = true
	return _node, nil
}

func (isc *IndividualSportCreate) createSpec() (*IndividualSport, *sqlgraph.CreateSpec) {
	var (
		_node = &IndividualSport{config: isc.config}
		_spec = sqlgraph.NewCreateSpec(individualsport.Table, sqlgraph.NewFieldSpec(individualsport.FieldID, field.TypeInt))
	)
	if value, ok := isc.mutation.Country(); ok {
		_spec.SetField(individualsport.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := isc.mutation.Sport(); ok {
		_spec.SetField(individualsport.FieldSport, field.TypeString, value)
		_node.Sport = value
	}
	if value, ok := isc.mutation.Gold(); ok {
		_spec.SetField(individualsport.FieldGold, field.TypeInt, value)
		_node.Gold = value
	}
	if value, ok := isc.mutation.Silver(); ok {
		_spec.SetField(individualsport.FieldSilver, field.TypeInt, value)
		_node.Silver = value
	}
	if value, ok := isc.mutation.Bronze(); ok {
		_spec.SetField(individualsport.FieldBronze, field.TypeInt, value)
		_node.Bronze = value
	}
	if value, ok := isc.mutation.Points(); ok {
		_spec.SetField(individualsport.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := isc.mutation.TotalScore(); ok {
		_spec.SetField(individualsport.FieldTotalScore, field.TypeInt, value)
		_node.TotalScore = value
	}
	if value, ok := isc.mutation.Population(); ok {
		_spec.SetField(individualsport.FieldPopulation, field.TypeInt, value)
		_node.Population = value
	}
	if value, ok := isc.mutation.PerCapita(); ok {
		_spec.SetField(individualsport.FieldPerCapita, field.TypeFloat64, value)
		_node.PerCapita = value
	}
	return _node, _spec
}

// IndividualSportCreateBulk is the builder for creating many IndividualSport entities in bulk.
type IndividualSportCreateBulk struct {
	config
	err      error
	builders []*IndividualSportCreate
}

// Save creates the IndividualSport entities in the database.
func (iscb *IndividualSportCreateBulk) Save(ctx context.Context) ([]*IndividualSport, error) {
	if iscb.err != nil {
		return nil, iscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iscb.builders))
	nodes := make([]*IndividualSport, len(iscb.builders))
	mutators := make([]Mutator, len(iscb.builders))
	for i := range iscb.builders {
		func(i int, root context.Context) {
			builder := iscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndividualSportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iscb *IndividualSportCreateBulk) SaveX(ctx context.Context) []*IndividualSport {
	v, err := iscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iscb *IndividualSportCreateBulk) Exec(ctx context.Context) error {
	_, err := iscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iscb *IndividualSportCreateBulk) ExecX(ctx context.Context) {
	if err := iscb.Exec(ctx); err != nil {
		panic(err)
	}
}
