// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CombinedSport is the predicate function for combinedsport builders.
type CombinedSport func(*sql.Selector)

// IndividualSport is the predicate function for individualsport builders.
type IndividualSport func(*sql.Selector)

// TeamSport is the predicate function for teamsport builders.
type TeamSport func(*sql.Selector)
